// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shteqzkuxxsagvsyatzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNodGVxemt1eHhzYWd2c3lhdHpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzUzMDQsImV4cCI6MjA2NDUxMTMwNH0.5suDD8OhEchc6K_rweGjohRg9dCsmnt6OpcJ3AcZdYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);